export { default as Index } from './Index/index'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as My } from './My'
export { default as NotFound } from './NotFound'