export { default as Index } from './Index/index'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as My } from './My'
export { default as Create } from './Create'
export { default as Detail } from './Detail'
export { default as Edit } from './Edit'
export { default as User } from './User'

export { default as NotFound } from './NotFound'